easy_admin:
   site_name: "Allo'Mecano"
       
   design:
        brand_color: '#1ABC9C'
        menu:
          - { entity: 'Commentaire' }
          - { entity: 'Garage' }
          - { entity: 'Image' }
          - { entity: 'Service' }
          - { entity: 'Utilisateur' }
          - { entity: 'Visit' }
          - { label: 'Accueil', url: 'http://127.0.0.1:8001', rel: 'home' }

   entities:

      Commentaire:
            class: App\Entity\Comment
            list:
                fields: ['id', 'content', {property: 'rate', label: 'Note'}, {property: 'createdAt', label: 'date de création'} , {property: 'rate', label: 'Note'}, {property: 'enable', label: 'Activer o/n'}, 'user', 'garage']
      Garage:
            class: App\Entity\Garage
            list:
                fields: ['id', {property: 'name', label: 'Nom du garage'}, {property: 'adress', label: 'Adresse'}, 'gps', {property: 'createdAt', label: 'date de création'},{property: 'mobility', label: 'Mobilité'}, 'distance', 'visit']
      Image:
            class: App\Entity\Image
            list:
                fields: ['id', 'url', {property: 'createdAt', label: 'date de création'}, 'garage']
      Service:
            class: App\Entity\Service
            list:
                fields: ['id', {property: 'name', label: 'Nom du service'}, {property: 'price', label: 'Prix du service'}, {property: 'createdAt', label: 'Date de création'}, 'garages', 'visits']
      Utilisateur:
            class: App\Entity\User
            list:
                fields: ['id', {property: 'username', label: 'Pseudo'}, {property: 'firstname', label: 'Prénom'}, {property: 'lastname', label: 'Nom'}, {property: 'roles', label: 'Rôle'}, {property: 'phone', label: 'Téléphone'}, {property: 'adress', label: 'Adresse'}]
      Visit:
            class: App\Entity\Visit
            list:
                fields: ['id', 'user', {property: 'date', label: 'Date de rendez-vous'}, {property: 'time', label: 'Heure de rendez-vous'}, {property: 'reservation date', label: 'Date de réservation'}, {property: 'created at', label: 'Date de création'}, 'garage', 'service']

